const assert = require('node:assert/strict');
const {assertResponsive} = require('./responsive.cjs');
async function exerciseAccountDeletion({admin, hub, base, device, expect}) {
  const victim = await hub.auth.create('demo-delete-account', 'Fictional-password-123', 'observer');
  const signedIn = await device(victim.username, true);
  await admin.goto(base + '/accounts.html');
  const ownId = hub.auth.list().find(user => user.username === 'demo-admin').id;
  const own = admin.locator(`.account-card[data-id="${ownId}"]`);
  const target = admin.locator(`.account-card[data-id="${victim.id}"]`);
  for (const form of [own, target]) await form.locator('..').locator('summary').first().click();
  await expect(own.locator('[data-delete-account]')).toBeDisabled();
  await own.locator('details.account-password summary').click();
  await own.locator('input[type=password]').fill('Fictional-unsaved-draft-123');
  await target.locator('select[aria-label="Роля"]').selectOption('operator');
  const button = target.locator('[data-delete-account]');
  admin.once('dialog', async dialog => { assert.equal(dialog.type(), 'confirm'); assert.ok(dialog.message().includes(victim.username)); await dialog.dismiss(); });
  await button.click(); await expect(target).toBeVisible(); await expect(button).toBeEnabled();
  assert.ok(hub.auth.list().some(user => user.id === victim.id));
  await expect(target.locator('select[aria-label="Роля"]')).toHaveValue('operator');
  await admin.setViewportSize({width: 320, height: 900}); await assertResponsive(admin, 'Account deletion at 320px');
  await admin.locator('[data-hub-language=en]').click(); await expect(button).toHaveText('Delete account');
  await admin.route('**/api/accounts/' + victim.id, route => route.abort());
  admin.once('dialog', async dialog => { assert.match(dialog.message(), /Delete account "demo-delete-account"/); assert.match(dialog.message(), /History is retained/); await dialog.accept(); });
  await button.click(); await expect(target.locator('.account-feedback')).not.toBeEmpty(); await expect(button).toBeEnabled();
  await expect(target.locator('select[aria-label="Role"]')).toHaveValue('operator');
  await expect(own.locator('input[type=password]')).toHaveValue('Fictional-unsaved-draft-123');
  await admin.unroute('**/api/accounts/' + victim.id);
  await admin.locator('#accountSearch').fill(victim.username);
  admin.once('dialog', dialog => dialog.accept()); await button.click();
  await expect(admin.locator('#accountMessage')).toHaveText('Account deleted.');
  await expect(target).toHaveCount(0); await expect(admin.locator('#accountEmpty')).toBeVisible();
  await expect(admin.locator('#accountCount')).toHaveText('0 / ' + hub.auth.list().length);
  await expect(signedIn).toHaveURL(base + '/login.html');
  await admin.locator('#accountSearch').fill('');
  await expect(own.locator('input[type=password]')).toHaveValue('Fictional-unsaved-draft-123');
  await admin.reload(); await expect(target).toHaveCount(0);
  await admin.locator('[data-hub-language=bg]').click();
}
module.exports = {exerciseAccountDeletion};
