const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {randomUUID} = require('node:crypto');
const {openStore} = require('../../server/store.cjs');
const {accounts} = require('../../server/accounts.cjs');
const {createTasks} = require('../../server/tasks.cjs');
const password = 'Fictional-password-123';
test('deleted identities and historical assignments survive reopen; an in-flight password change cannot restore access', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hub-delete-test-'));
  let store = openStore(path.join(dir, 'demo.sqlite'));
  t.after(() => { store.db.close(); fs.rmSync(dir, {recursive: true, force: true}); });
  let auth = accounts(store);
  const admin = await auth.create('demo-admin', password, 'admin');
  const chief = await auth.create('demo-chief', password, 'operator', admin, {}, () => {}, {taskSupervisor: true, taskTeam: 'А'});
  const session = await auth.login(chief.username, password);
  let tasks = createTasks(store, {now: () => Date.parse('2026-12-01T07:00:00+02:00')});
  tasks.create({requestId: randomUUID(), title: 'Fictional historical task', description: '', priority: 'normal', assigneeId: chief.id, participantIds: [], kind: 'global', repeat: 'once', dueDate: '2026-12-02', dueTime: '17:00'}, admin);
  const history = tasks.list(admin).items;
  const update = auth.update(chief.id, {password: 'Fictional-replacement-123', active: true}, admin);
  auth.remove(chief.id, admin);
  await assert.rejects(update, {code: 'NOT_FOUND'});
  assert.equal(auth.session(session.token), null);
  assert.deepEqual(tasks.list(admin).items, history);
  assert.ok(!tasks.list(admin).supervisors.some(user => user.id === chief.id));
  store.db.close(); store = openStore(path.join(dir, 'demo.sqlite')); auth = accounts(store); tasks = createTasks(store, {now: () => Date.parse('2026-12-01T07:00:00+02:00')});
  assert.deepEqual(auth.list().map(user => user.username), ['demo-admin']);
  assert.equal(auth.session(session.token), null);
  await assert.rejects(auth.login(chief.username, password), {code: 'INVALID_LOGIN'});
  assert.deepEqual(tasks.list(admin).items, history);
  assert.ok((await auth.create('demo-new-chief', password, 'operator')).id > chief.id);
  assert.throws(() => auth.remove(admin.id, chief), {code: 'FORBIDDEN'});
});
